base_url = "http://dannyandrews.net/"
title = "Danny Andrews' Blog"
description = "A collection of articles related to software development"
default_language = "en"
generate_rss = true
theme = "even"
highlight_code = true
build_search_index = true
taxonomies = [
  {name = "tags", rss = true}
]
compile_sass = true

[extra]
even_menu = [
  {url = "https://github.com/danny-andrews/", name = "GitHub"},
  {url = "https://www.linkedin.com/in/danielandrews91/", name = "LinkedIn"}
]
even_title = "Danny Andrews' Blog"
