base_url = "https://dannyandrews.net/"
title = "Fashionably Early"
description = "Articles related to software development"
default_language = "en"
generate_feed = true
build_search_index = true
taxonomies = [{ name = "tags", feed = true }]
compile_sass = true

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]
footer_links = [
  { url = "https://github.com/danny-andrews/", name = "GitHub" },
  { url = "https://www.linkedin.com/in/danielandrews91/", name = "LinkedIn" },
]
author = "Danny Andrews"
footer = { info = "Built with Zola." }

[link_checker]
skip_anchor_prefixes = [
  "https://github.com/gajus",
  "https://github.com/webpack-contrib",
]
