[build]
publish = "public"
command = "zola build"

[build.environment]
ZOLA_VERSION = "0.11.0"

[[redirects]]
from = "https://task-time.danny-andrews.net/*"
to = "https://task-time.netlify.app/:splat"
status = 200
